### ISSUE TITLE
Rotate Session

### ISSUE THREAD

**Issue by wshager** [persvr/pintura#35]
When the Session file gets too large, persvr will hang with a "RangeError: Maximum call stack size exceeded"

**Comment by wshager** [comment]
Sorry for the delay, but I'm afraid I don't understand how this works. I would simply like to prevent the /data/Session file to grow beyond a certain size, but I don't see how this can be done with a validate method. Moreover, I think this should be done by default.

**Comment by neonstalwart** [comment]
maybe think of `validate` as the wrong name for something which might be better called `reap` - although `validate` is not such a bad name since it validates all the existing sessions and removes the ones which are no longer valid.  

by providing the `validate` method on your session model it will be called periodically for it to do the work of reaping invalid sessions.  that is why it is how you prevent your file growing.

an example:

```js
var model = require("perstore/model").Model,
	sessionStore = require('../store/session'),
	Query = require('rql/query').Query;

module.exports = model(sessionStore, {
	properties: {
		// this is the id of the user associated with the session
		user: {
			type: 'string'
		}
	},

	validate: function () {
		var now = new Date(),
			query = new Query();

		query = query.lt('expires', now.toISOString());
		return sessionStore.ready().then(function () {
			sessionStore.query(query).then(function(sessions) {
				sessions.forEach(function (session) {
					console.log('reaping session', session.id, session.expires);
					sessionStore['delete'](session.id);
				});
			});
		});
	}
});
```

does that help?  am i misunderstanding what you want?

**Comment by wshager** [comment]
Thanks, that's what I mean. Any particular reason this can't be set on the default session model? 

I also think if this would be a default perstore model the file would not be cleaned up this way, right? If anything, it would add extra __deleted lines.

**Comment by wshager** [comment]
Ok another noob question: where should this model be set? I have a custom user facet in my persevere app, but that just references `require("pintura/jsgi/session").getCurrentSession()`.

Oviously I don't want to set it in pintura, as I want to keep that package unmodified. And I can't seem to set it on the pintura app config, because jsgi/session doesn't use it.

**Comment by neonstalwart** [comment]
> Any particular reason this can't be set on the default session model?

maybe it could but there is not going to be a one-size-fits-all solution

1. invalidating sessions based on time is only one way to invalidate a session.  some sessions may never expire, some may become invalid once the same user creates another session, some may expire when a user revokes them, ...
1. not all store interfaces are quite equal - you can see i have to call `sessionStore.ready().then` before interacting with the store.  this is because it's a mongo store that initializes asynchronously so it's not ready as soon as it's constructed.

since the logic for invalidating sessions is potentially unique per application, it makes sense to put this logic in a session model.

> I also think if this would be a default perstore model the file would not be cleaned up this way, right? If anything, it would add extra __deleted lines.

honestly, i'm not familiar with the internals of the default store - i don't use it so i can't say.  the particular example i pasted above was using mongodb.  i've also used leveldb and in-memory stores to back my session model at various times.  my current app doesn't even use sessions, instead the user includes an Authentication header with a JWT i issue to them and makes it possible for me to identify who they are - everything is stateless, so identity is the only context i need to determine when a request is made.

> Oviously I don't want to set it in pintura, as I want to keep that package unmodified

actually... you *do* want to customize that.  use the existing pintura.js file as a template, copy it to your app, and modify it as needed.  i'm yet to build a non-trivial app with persevere which doesn't have it's own customized "pipeline" of jsgi apps (which also usually includes building my own customized jsgi apps to include in that pipeline).

```js
// app/pintura.js
// ...
       require('pintura/jsgi/session').Session({
         model: require('./model/Session') // this is the file in my previous comment
       }, 
           // ...
       )
// ...
```

fyi - configuring this pipeline is even simpler in the dev-2.0 branch

**Comment by wshager** [comment]
Ok I'll use mongodb then. Indeed some kind of template for pintura pipelines would be great. Thanks!
